
# Load starship
eval "$(starship init zsh)"

# User configuration
alias ls="ls --color=auto"
alias l="ls -lah"
alias la="ls -a"
alias rf="rm -rf"
alias ff=fastfetch
alias pf=pfetch
alias nv=nvim
alias snv="EDITOR=nvim sudo -e"
alias nj=ninja

alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gpu="git push"
alias gpl="git pull"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

