name: Check Version Action

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python-semver
        run: |
          apt update
          apt install -y python3-semver

      - name: Verify incremented version
        run: python ./scripts/check_version.py $(git describe --tags --abbrev=0)
